spring.application.name=Sample Pokedex

# H2 Database configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/pokedex_db
spring.datasource.username=aleph
spring.datasource.password=qwe123ASD!@#

# The driver class
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
# 'update' is good for development. It creates/updates tables automatically.
# (In production, you would use 'validate' and manage scripts with a tool like Flyway or Liquibase)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (helpful for debugging)
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Custom API Security Key
api.security.key=secret-api-key

# Tell Jackson to automatically use snake_case for all JSON requests and responses
spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Default Admin Credentials setup
app.admin.username=${DEFAULT_ADMIN_USERNAME}
app.admin.password=${DEFAULT_ADMIN_PASSWORD}